### ISSUE TITLE
【NPM引入加速】可以通过UNPKG的全球CDN进行引入

### ISSUE THREAD

**Issue by swift-fs** [KonghaYao/chinese-free-web-font-storage#47]
我刚查看官网文章：**不建议通过`npm包`的方式引入字体文件**，考虑到的是大小和速度问题。可以使用[https://www.unpkg.com/](https://www.unpkg.com/)来进行CDN加速，比如引入猫啃字体：

```css
@import url("https://www.unpkg.com/@chinese-fonts/mkwtyt@1.4.0/dist/MaoKenTangYuan/result.css");

:root {
  --vp-font-family-base: 'MaoKenTangYuan (beta)';
  /* --vp-font-family-mono: 'jiangxizhuokai'; */
}
```
